# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  staging_deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Deploy into Firebase Staging
          command: bash .circleci/staging_deploy.sh
  production_deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Deploy into Firebase Production
          command: bash .circleci/production_deploy.sh

workflows:
  version: 2
  staging_update:
    jobs:
      - staging_deploy:
          filters:
            branches:
              only:
                - staging
  production_update:
    jobs:
      - production_deploy:
          filters:
            branches:
              only:
                - master
